# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node GitHub CI

on:
  push:
    branches: [ master ]

jobs:
  # Test
  test:
    runs-on: ubuntu-latest #test sur Linux , mais on peux aussi sur windows : windows-latest ou mac : macos-latest
    
    strategy:
      matrix:
        node-version: [10.x, 12.x]
        
    # Tache a effecter dans ce job
    steps:
    - uses: actions/checkout@v2
      
    - name: Utilisation de node version ${{ matrix.node_version }}
      # L'action sera de mettre en plce Node à la version donnée plus bas (node-version)
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
      
    # Nom pour cette tâche
    - name: npm install and test
      # Commandes exécutées
      run: |
        npm install
        npm test
